version: "3"

services:
  portalzs:
    container_name: portalzs_client
    image: node:10
    ports:
      - "3000:3000"
    command: sh -c "npm i && npm run start"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    stdin_open: true
